"use client";

import { motion } from "framer-motion";
import { Sparkles, ArrowRight } from "lucide-react";
import { cn } from "@/lib/utils";
import { getAllVerticals } from "@/lib/verticals/registry";
import type { VerticalDefinition } from "@/lib/verticals/types";

// Dynamic icon import for verticals
import { Building2, Home, Wrench, Stethoscope, Scale, Car } from "lucide-react";

const ICON_MAP: Record<string, React.ComponentType<{ className?: string }>> = {
    Building2,
    Home,
    Wrench,
    Stethoscope,
    Scale,
    Car,
};

interface PathSelectionScreenProps {
    onSelectAutoGenerated: () => void;
    onSelectVertical: (verticalId: string) => void;
}

export function PathSelectionScreen({
    onSelectAutoGenerated,
    onSelectVertical,
}: PathSelectionScreenProps) {
    const verticals = getAllVerticals();

    return (
        <div className="flex min-h-screen items-center justify-center p-6">
            <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.5 }}
                className="w-full max-w-3xl"
            >
                {/* Header */}
                <div className="mb-8 text-center">
                    <h1 className="text-2xl font-bold text-gray-900">
                        How would you like to set up your AI agents?
                    </h1>
                    <p className="mt-2 text-sm text-gray-500">
                        Choose the path that best fits your business
                    </p>
                </div>

                {/* Cards Grid */}
                <div className="grid gap-4 md:grid-cols-2">
                    {/* Auto-Generated Card */}
                    <PathCard
                        title="AI Auto-Setup"
                        description="Paste your website URL and our AI will analyze your business, generate custom agents, and configure everything automatically."
                        icon={
                            <Sparkles className="h-6 w-6 text-violet-600" />
                        }
                        badge="Any Industry"
                        badgeColor="bg-violet-50 text-violet-600 ring-violet-200"
                        onClick={onSelectAutoGenerated}
                        delay={0.1}
                    />

                    {/* Vertical Cards — auto-rendered from registry */}
                    {verticals.map((vertical, index) => (
                        <VerticalCard
                            key={vertical.id}
                            vertical={vertical}
                            onClick={() => onSelectVertical(vertical.id)}
                            delay={0.2 + index * 0.1}
                        />
                    ))}
                </div>
            </motion.div>
        </div>
    );
}

// ─── PATH CARD (generic) ───

function PathCard({
    title,
    description,
    icon,
    badge,
    badgeColor,
    onClick,
    delay = 0,
}: {
    title: string;
    description: string;
    icon: React.ReactNode;
    badge: string;
    badgeColor: string;
    onClick: () => void;
    delay?: number;
}) {
    return (
        <motion.button
            initial={{ opacity: 0, y: 15 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.4, delay }}
            onClick={onClick}
            className={cn(
                "group relative flex flex-col items-start rounded-2xl border border-gray-200 bg-white p-6 text-left shadow-sm",
                "transition-all duration-200 hover:border-violet-300 hover:shadow-md"
            )}
        >
            {/* Icon */}
            <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-violet-50">
                {icon}
            </div>

            {/* Title + Badge */}
            <div className="mt-4 flex items-center gap-2">
                <h3 className="text-base font-semibold text-gray-900">
                    {title}
                </h3>
                <span
                    className={cn(
                        "rounded-full px-2 py-0.5 text-[10px] font-medium ring-1",
                        badgeColor
                    )}
                >
                    {badge}
                </span>
            </div>

            {/* Description */}
            <p className="mt-2 text-sm leading-relaxed text-gray-500">
                {description}
            </p>

            {/* CTA */}
            <div className="mt-4 flex items-center gap-1.5 text-sm font-medium text-violet-600 transition-colors group-hover:text-violet-700">
                Get started
                <ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-0.5" />
            </div>
        </motion.button>
    );
}

// ─── VERTICAL CARD ───

function VerticalCard({
    vertical,
    onClick,
    delay,
}: {
    vertical: VerticalDefinition;
    onClick: () => void;
    delay: number;
}) {
    const Icon = ICON_MAP[vertical.icon] || Building2;

    return (
        <PathCard
            title={vertical.name}
            description={vertical.description}
            icon={<Icon className="h-6 w-6 text-emerald-600" />}
            badge={vertical.badge}
            badgeColor="bg-emerald-50 text-emerald-600 ring-emerald-200"
            onClick={onClick}
            delay={delay}
        />
    );
}
