"use client";

import { motion } from "framer-motion";
import { Sparkles, ArrowRight, Calendar } from "lucide-react";
import { cn } from "@/lib/utils";
import { getAllVerticals } from "@/lib/verticals/registry";
import type { VerticalDefinition } from "@/lib/verticals/types";

import { Building2, Home, Wrench, Stethoscope, Scale, Car, Rocket, Cloud } from "lucide-react";

const ICON_MAP: Record<string, React.ComponentType<{ className?: string }>> = {
    Building2,
    Home,
    Wrench,
    Stethoscope,
    Scale,
    Car,
    Rocket,
    Cloud,
};

interface PathSelectionScreenProps {
    onSelectScheduleCall?: () => void;
    onSelectAutoGenerated: () => void;
    onSelectVertical: (verticalId: string) => void;
    isAdmin?: boolean;
}

export function PathSelectionScreen({
    onSelectScheduleCall,
    onSelectAutoGenerated,
    onSelectVertical,
    isAdmin = false,
}: PathSelectionScreenProps) {
    const verticals = getAllVerticals();

    return (
        <div className="flex min-h-screen items-center justify-center p-6">
            <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.5 }}
                className="w-full max-w-3xl"
            >
                <div className="mb-8 text-center">
                    <h1 className="text-2xl font-bold text-gray-900">
                        How would you like to set up your AI agents?
                    </h1>
                    <p className="mt-2 text-sm text-gray-500">
                        Choose the path that best fits your business
                    </p>
                </div>

                <div className="grid gap-4 md:grid-cols-2">
                    {onSelectScheduleCall && (
                        <PathCard
                            title="Schedule Onboarding Call"
                            description="Book a 15-30 min call with our onboarding team. We'll set up your AI agents live with you, configure everything for your business, and have you live by the end of the call."
                            icon={
                                <Calendar className="h-6 w-6 text-emerald-600" />
                            }
                            badge="Recommended"
                            badgeColor="bg-emerald-50 text-emerald-700 ring-emerald-200"
                            onClick={onSelectScheduleCall}
                            delay={0.05}
                        />
                    )}

                    <PathCard
                        title="AI Auto-Setup"
                        description="Paste your website URL and our AI will analyze your business, generate custom agents, and configure everything automatically."
                        icon={
                            <Sparkles
                                className={cn(
                                    "h-6 w-6",
                                    isAdmin ? "text-emerald-600" : "text-gray-400"
                                )}
                            />
                        }
                        badge={isAdmin ? "Admin Only" : "Coming Soon"}
                        badgeColor={
                            isAdmin
                                ? "bg-indigo-50 text-indigo-700 ring-indigo-200"
                                : "bg-gray-100 text-gray-500 ring-gray-200"
                        }
                        onClick={onSelectAutoGenerated}
                        disabled={!isAdmin}
                        delay={0.1}
                    />

                    {verticals.map((vertical, index) => (
                        <VerticalCard
                            key={vertical.id}
                            vertical={vertical}
                            onClick={() => onSelectVertical(vertical.id)}
                            delay={0.2 + index * 0.1}
                        />
                    ))}
                </div>
            </motion.div>
        </div>
    );
}

function PathCard({
    title,
    description,
    icon,
    badge,
    badgeColor,
    onClick,
    delay = 0,
    disabled = false,
}: {
    title: string;
    description: string;
    icon: React.ReactNode;
    badge: string;
    badgeColor: string;
    onClick: () => void;
    delay?: number;
    disabled?: boolean;
}) {
    return (
        <motion.button
            initial={{ opacity: 0, y: 15 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.4, delay }}
            onClick={disabled ? undefined : onClick}
            disabled={disabled}
            aria-disabled={disabled}
            className={cn(
                "group relative flex flex-col items-start rounded-2xl border border-gray-200 bg-white p-6 text-left shadow-sm",
                disabled
                    ? "cursor-not-allowed opacity-60"
                    : "transition-all duration-200 hover:border-emerald-300 hover:shadow-md"
            )}
        >
            <div
                className={cn(
                    "flex h-12 w-12 items-center justify-center rounded-xl",
                    disabled ? "bg-gray-100" : "bg-emerald-50"
                )}
            >
                {icon}
            </div>

            <div className="mt-4 flex items-center gap-2">
                <h3
                    className={cn(
                        "text-base font-semibold",
                        disabled ? "text-gray-500" : "text-gray-900"
                    )}
                >
                    {title}
                </h3>
                <span
                    className={cn(
                        "rounded-full px-2 py-0.5 text-[10px] font-medium ring-1",
                        badgeColor
                    )}
                >
                    {badge}
                </span>
            </div>

            <p
                className={cn(
                    "mt-2 text-sm leading-relaxed",
                    disabled ? "text-gray-400" : "text-gray-500"
                )}
            >
                {description}
            </p>

            {disabled ? (
                <div className="mt-4 flex items-center gap-1.5 text-sm font-medium text-gray-400">
                    Coming soon
                </div>
            ) : (
                <div className="mt-4 flex items-center gap-1.5 text-sm font-medium text-emerald-600 transition-colors group-hover:text-emerald-700">
                    Get started
                    <ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-0.5" />
                </div>
            )}
        </motion.button>
    );
}

function VerticalCard({
    vertical,
    onClick,
    delay,
}: {
    vertical: VerticalDefinition;
    onClick: () => void;
    delay: number;
}) {
    const Icon = ICON_MAP[vertical.icon] || Building2;

    return (
        <PathCard
            title={vertical.name}
            description={vertical.description}
            icon={<Icon className="h-6 w-6 text-emerald-600" />}
            badge={vertical.badge}
            badgeColor="bg-emerald-50 text-emerald-600 ring-emerald-200"
            onClick={onClick}
            delay={delay}
        />
    );
}
