"use client";

import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { motion } from "framer-motion";
import { ArrowLeft, Loader2, X } from "lucide-react";
import Link from "next/link";
import { PathSelectionScreen } from "@/components/onboarding-v2/components/path-selection-screen";
import { VerticalForm } from "@/components/onboarding-v2/components/vertical-form";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import {
    createSingleAgent,
    type CreateSingleAgentInput,
} from "@/app/actions/create-single-agent-actions";
import type { REInvestorFormData } from "@/lib/verticals/types";

type Phase =
    | "path_selection"
    | "generic_form"
    | "vertical_form"
    | "deploying"
    | "error";

interface NewAgentWizardProps {
    clientId: string;
    clientName: string;
    tenantTimezone: string;
}

export function NewAgentWizard({
    clientId,
    clientName,
    tenantTimezone,
}: NewAgentWizardProps) {
    const router = useRouter();
    const [phase, setPhase] = useState<Phase>("path_selection");
    const [selectedVerticalId, setSelectedVerticalId] = useState<string | null>(
        null
    );
    const [errorMessage, setErrorMessage] = useState<string | null>(null);
    const [isPending, startTransition] = useTransition();

    const deploy = (input: CreateSingleAgentInput) => {
        setPhase("deploying");
        setErrorMessage(null);
        startTransition(async () => {
            const result = await createSingleAgent(clientId, input);
            if (!result.success || !result.vapiId) {
                setErrorMessage(result.error || "Failed to create agent");
                setPhase("error");
                return;
            }
            router.push(`/client/${clientId}/agents/${result.vapiId}`);
        });
    };

    return (
        <div className="fixed inset-0 z-50 overflow-auto bg-gray-50">
            {/* Close button */}
            <Link
                href={`/client/${clientId}/agents`}
                className="fixed right-6 top-6 z-20 flex h-9 w-9 items-center justify-center rounded-full bg-white text-gray-500 shadow-sm ring-1 ring-gray-200 transition hover:bg-gray-100 hover:text-gray-700"
                aria-label="Cancel"
            >
                <X className="h-4 w-4" />
            </Link>

            {phase === "path_selection" && (
                <PathSelectionScreen
                    onSelectAutoGenerated={() => setPhase("generic_form")}
                    onSelectVertical={(verticalId) => {
                        setSelectedVerticalId(verticalId);
                        setPhase("vertical_form");
                    }}
                />
            )}

            {phase === "generic_form" && (
                <GenericAgentForm
                    clientName={clientName}
                    onBack={() => setPhase("path_selection")}
                    onSubmit={(agentName, agentType) =>
                        deploy({ kind: "generic", agentType, agentName })
                    }
                    submitting={isPending}
                />
            )}

            {phase === "vertical_form" && selectedVerticalId && (
                <VerticalForm
                    verticalId={selectedVerticalId}
                    initialData={{
                        companyName: clientName,
                        timezone: tenantTimezone,
                    }}
                    onBack={() => setPhase("path_selection")}
                    onContinue={(formData: REInvestorFormData) =>
                        deploy({
                            kind: "vertical_re",
                            formData,
                            agentName: `${formData.companyName} - Inbound Receptionist`,
                        })
                    }
                />
            )}

            {phase === "deploying" && <Deploying />}

            {phase === "error" && (
                <ErrorScreen
                    message={errorMessage || "Something went wrong"}
                    onRetry={() => setPhase("path_selection")}
                    onCancelHref={`/client/${clientId}/agents`}
                />
            )}
        </div>
    );
}

// ─── GENERIC "BUILD YOUR OWN" MINI-FORM ───

function GenericAgentForm({
    clientName,
    onBack,
    onSubmit,
    submitting,
}: {
    clientName: string;
    onBack: () => void;
    onSubmit: (name: string, type: "inbound" | "outbound") => void;
    submitting: boolean;
}) {
    const [agentType, setAgentType] = useState<"inbound" | "outbound">(
        "inbound"
    );
    const [agentName, setAgentName] = useState(`${clientName} - Inbound`);
    const [touchedName, setTouchedName] = useState(false);

    const onTypeChange = (next: "inbound" | "outbound") => {
        setAgentType(next);
        if (!touchedName) {
            setAgentName(
                `${clientName} - ${next === "inbound" ? "Inbound" : "Outbound"}`
            );
        }
    };

    const canSubmit = agentName.trim().length >= 2 && !submitting;

    return (
        <div className="flex min-h-screen items-center justify-center p-6">
            <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.4 }}
                className="w-full max-w-lg rounded-2xl border border-gray-200 bg-white p-8 shadow-sm"
            >
                <button
                    onClick={onBack}
                    className="mb-6 flex items-center gap-1.5 text-sm text-gray-500 hover:text-gray-700"
                >
                    <ArrowLeft className="h-4 w-4" />
                    Back
                </button>

                <h1 className="text-2xl font-bold text-gray-900">
                    Build your own agent
                </h1>
                <p className="mt-1.5 text-sm text-gray-500">
                    We'll use your saved business profile as the starting point.
                </p>

                <div className="mt-8 space-y-6">
                    {/* Agent type */}
                    <div>
                        <label className="text-sm font-medium text-gray-700">
                            Agent type
                        </label>
                        <div className="mt-2 grid grid-cols-2 gap-2">
                            {(["inbound", "outbound"] as const).map((type) => (
                                <button
                                    key={type}
                                    onClick={() => onTypeChange(type)}
                                    className={`rounded-lg border px-4 py-3 text-sm font-medium transition ${
                                        agentType === type
                                            ? "border-emerald-500 bg-emerald-50 text-emerald-700 ring-2 ring-emerald-500/20"
                                            : "border-gray-200 bg-white text-gray-600 hover:border-gray-300"
                                    }`}
                                >
                                    {type === "inbound"
                                        ? "Inbound (answers calls)"
                                        : "Outbound (places calls)"}
                                </button>
                            ))}
                        </div>
                    </div>

                    {/* Agent name */}
                    <div>
                        <label className="text-sm font-medium text-gray-700">
                            Agent name
                        </label>
                        <Input
                            className="mt-2"
                            value={agentName}
                            onChange={(e) => {
                                setAgentName(e.target.value);
                                setTouchedName(true);
                            }}
                            placeholder="e.g. Nashville Homebuyers - Front Desk"
                        />
                        <p className="mt-1.5 text-xs text-gray-400">
                            Shown in your dashboard and in VAPI.
                        </p>
                    </div>

                    {/* Submit */}
                    <div className="flex items-center justify-end gap-3 pt-4">
                        <Button variant="outline" onClick={onBack}>
                            Cancel
                        </Button>
                        <Button
                            disabled={!canSubmit}
                            onClick={() => onSubmit(agentName.trim(), agentType)}
                        >
                            {submitting ? (
                                <>
                                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                                    Creating...
                                </>
                            ) : (
                                "Create agent"
                            )}
                        </Button>
                    </div>
                </div>
            </motion.div>
        </div>
    );
}

// ─── DEPLOYING ───

function Deploying() {
    return (
        <div className="flex min-h-screen flex-col items-center justify-center">
            <motion.div
                initial={{ opacity: 0, scale: 0.95 }}
                animate={{ opacity: 1, scale: 1 }}
                className="flex flex-col items-center gap-4"
            >
                <div className="flex h-16 w-16 items-center justify-center rounded-full bg-emerald-50 ring-2 ring-emerald-200">
                    <Loader2 className="h-7 w-7 animate-spin text-emerald-600" />
                </div>
                <div className="text-center">
                    <p className="text-lg font-semibold text-gray-900">
                        Creating your agent…
                    </p>
                    <p className="mt-1 text-sm text-gray-500">
                        Wiring up the voice, prompt, and calendar tools.
                    </p>
                </div>
            </motion.div>
        </div>
    );
}

// ─── ERROR ───

function ErrorScreen({
    message,
    onRetry,
    onCancelHref,
}: {
    message: string;
    onRetry: () => void;
    onCancelHref: string;
}) {
    return (
        <div className="flex min-h-screen items-center justify-center p-6">
            <div className="w-full max-w-md rounded-2xl border border-red-200 bg-white p-8 shadow-sm">
                <h1 className="text-lg font-semibold text-gray-900">
                    Couldn't create agent
                </h1>
                <p className="mt-2 text-sm text-red-600">{message}</p>
                <div className="mt-6 flex gap-3">
                    <Button onClick={onRetry}>Try again</Button>
                    <Link href={onCancelHref}>
                        <Button variant="outline">Back to agents</Button>
                    </Link>
                </div>
            </div>
        </div>
    );
}
